name: Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H makemytaxes.com >> ~/.ssh/known_hosts
          echo "SSH Key Setup Complete"

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no makemytaxes@makemytaxes.com "echo 'SSH connection successful'"

      - name: Deploy to GoDaddy
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete dist/ makemytaxes@makemytaxes.com:/home/makemytaxes/public_html/sadhcpa.com
