name: Deploy to GoDaddy cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}
        ssh-passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}

    - name: Deploy to GoDaddy cPanel
      run: |
        rsync -avz --delete --exclude '.git*' dist/ makemytaxes@sadhcpa.com:/home/makemytaxes/public_html/sadhcpa.com
